### ISSUE TITLE
Choosing which environments to show

### ISSUE THREAD

**Issue by celine168** [LibreTexts/default-env#10]
The default environment seems to be mostly working, asides from a bug with the R console about showing the banner.

Which environments should we choose to show?
The default environment contains the most packages/kernels so far.

The [Jupyter Docker Stacks](https://github.com/jupyter/docker-stacks) are pre-built and vary in the types of kernels they provide. They have less features than the default environment, i.e. they do not have the packages that professors want, but we could build Dockerfiles based on the Docker Stacks that add these packages. 

Another option is to only add `nb_conda_kernels` to the default Docker Stacks.

Do we want the additional environments to have less or more packages/kernels than the default environment? Any suggestions?

**Comment by moorepants** [comment]
For now we really only need to show the 1 default environment. What would be the reason for any others?

**Comment by celine168** [comment]
The Jupyter Docker Stacks include Spark and Tensorflow images, not sure if you're interested in those.

**Comment by moorepants** [comment]
I'd say not until a user requests that.
