### ISSUE TITLE
Could be cool to at RStudio sessions to the Hub

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/default-env#12]
There are tons of R users on campus and RStudio is likely the preferred interface. There is this: https://github.com/jupyterhub/jupyter-rsession-proxy that lets you run RStudio on the hub. I'd like to support it in the default environment if possible.

**Comment by moorepants** [comment]
It is also possible that this should be its own environment. Not sure.

**Comment by celine168** [comment]
Interesting, I will try adding it to the Dockerfile.

**Comment by celine168** [comment]
RStudio is available by interchanging `/lab` with `/rstudio` in the URL.
I have not figured out a way for packages like `r-shiny` and `r-shinydashboard` to work in JupyterLab. Web apps run under an IP address inside the container that's difficult to access like `http://127.0.0.1:<port>`. I suggest that anyone who wants to run a web app with R to use RStudio.

**Comment by moorepants** [comment]
Can you revert this? Maybe it has to do with the HTTP 500 errors I am getting?

**Comment by celine168** [comment]
For the sake of re-documenting on GitHub, I'll add here that I tried changing to custom error pages not related to RStudio, which caused the errors.

**Comment by moorepants** [comment]
The RStudio setup is super cool! Nice work on that. I thought I saw a button in the jupyterlab menu that would open it on the documentation. We'll want to figure out that.

**Comment by moorepants** [comment]
There is a button but it is in the old notebook interface. If you go to help>launch classic interface then go to the "new" button there you see rstudio and shiny listed.

**Comment by moorepants** [comment]
See this https://github.com/jupyterhub/jupyter-rsession-proxy/issues/59 seems like icons don't show in firefox 60??

**Comment by moorepants** [comment]
I'm running Firefox 68 and it doesn't work.

**Comment by moorepants** [comment]
I just tried in Chrome and do not see the icons.

**Comment by moorepants** [comment]
Installed
