### ISSUE TITLE
Conda channels in default-env

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/default-env#17]
I noticed that you install pymol via personal conda channel. I want to recommend that we only install packages in the default environment from the conda-forge channel (and maybe the default channel). It is not safe practice for us to install software from other arbitrary channels. If we need a package that is not in the conda-forge channel, it is best that we add that package to conda-forge then install from there. We should also avoid install development versions of packages. In general, the rule of thumb is that we only install pinned versions of released packages from the conda-forge channel or from apt-get. Otherwise we will run into incompatibility issues. I can talk more in person about this.

For packages that don't fit the default env we should make custom envs or ask the user to install the packages themselves in their environments.

**Comment by celine168** [comment]
Pymol is only available on the schrodinger or samoturk channels. Ehren Bucholtz requested pymol to be installed from the samoturk channel, which he said was from UC Irvine (I can't confirm this though).

As for rdkit and mordred, I believe those are available on conda-forge. I can check with Ehren if this is okay with him.

I installed ipymol from GitHub since it fixed a major bug (fetching a molecule/structure(?)) that was not available on a stable release on pip.

**Comment by moorepants** [comment]
I understand all of this, but I don't think it is in our best interest to support non-released software. I think we should have a policy that it must be in the conda-forge channel for us to install in the default-env. We should go ahead and make that policy now before we dig ourselves into a hole we don't want to be in.

conda forge offers these benefits 1) all packages are compatible with one another, 2) the package that is installed has been vetted by the conda forge community, 3) the package is maintained by the community, 4) only pinned released versions are available. For these reasons, we should stick to that channel only. Lastly, we don't want to be in the business of maintaining special installations of all these software packages that are compatible. It is outside our scope.

Please switch everything to conda-forge that can be and for the others, I'd prefer that we ask Ehren to have them added to conda forge. We can install from pip for now, but need to move to all conda-forge. The github version shouldn't be installed in our environment.

**Comment by moorepants** [comment]
I've proposed a policy in PR #18

**Comment by moorepants** [comment]
Fixed with #18. We will support Ehren's software but future software should follow this policy. I'll open and issue on getting pymol updated.
