### ISSUE TITLE
Can't seem to open octave in the terminal

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/default-env#22]
To reproduce, launch the default env, select terminal and type:

```
jovyan@jupyter-jasonmoore-40ucdavis-2eedu:~$ octave --no-gui
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
/home/conda/feedstock_root/build_artifacts/octave_1567285564915/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/octave-cli-4.2.1: failed to exec '/home/conda/feedstock_root/build_artifacts/octave_1567285564915/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/octave-cli-4.2.1'
octave: No such file or directory
```

**Comment by moorepants** [comment]
Octave seems to be generally unusable. Here is a console session, for example:
```
Octave Kernel v0.31.0 running GNU Octave v1

figure()

error: 'figure' undefined near line 1 column 1

octave_version()

error: 'octave_version' undefined near line 1 column 1

version()

error: 'version' undefined near line 1 column 1

uname()

ans =

  scalar structure containing the fields:

    sysname = Linux
    nodename = jupyter-jasonmoore-40ucdavis-2eedu
    release = 4.15.0-50-generic
    version = #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019
    machine = x86_64

version()

error: 'version' undefined near line 1 column 1

plot(1, 2)

error: 'plot' undefined near line 1 column 1
```

**Comment by moorepants** [comment]
This works in the terminal:
```
jovyan@jupyter-jasonmoore-40ucdavis-2eedu:~$ octave-cli -v
GNU Octave, version 4.2.1
Copyright (C) 2017 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.

Octave was configured for "x86_64-pc-linux-gnu".

Additional information about Octave is available at http://www.octave.org.

Please contribute if you find this software useful.
For more information, visit http://www.octave.org/get-involved.html

Read http://www.octave.org/bugs.html to learn how to submit bug reports.
jovyan@jupyter-jasonmoore-40ucdavis-2eedu:~$ octave-cli
GNU Octave, version 4.2.1
Copyright (C) 2017 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "x86_64-pc-linux-gnu".

Additional information about Octave is available at http://www.octave.org.

Please contribute if you find this software useful.
For more information, visit http://www.octave.org/get-involved.html

Read http://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.
```

**Comment by moorepants** [comment]
It may be smarter to install octave via apt instead of conda. I'm not sure if the conda-forge installation is functional.

**Comment by moorepants** [comment]
I opened this: https://github.com/conda-forge/octave-feedstock/issues/35

**Comment by moorepants** [comment]
Maybe we need to explicitly set this `OCTAVE_HOME` environment variable in the dockerfile as per: https://github.com/conda-forge/octave-feedstock/issues/31

**Comment by moorepants** [comment]
If we want to use the octave package from conda forge, we need to be setting `OCTAVE_HOME` in our installation script it seems: https://github.com/conda-forge/octave-feedstock/issues/35

**Comment by celine168** [comment]
Interesting. I'm going to test installing octave via apt.

**Comment by moorepants** [comment]
Setting octave_home might be the quicker solution.

**Comment by celine168** [comment]
I've tried setting `OCTAVE_HOME` to `/opt/conda/bin/octave` or `/opt/conda/bin/octave-cli` but neither seemed to work.

**Comment by celine168** [comment]
The octave apt install seems to work though.

**Comment by celine168** [comment]
I've updated the default environment, but it will not show up until we upgrade JupyterHub.
If you wish to test it out, I can send you a link to the default environment set up on my own JupyterHub.

**Comment by moorepants** [comment]
If you want to try some scrips to see if they work I have the ones for my class here: https://github.com/moorepants/eme171/tree/master/content/scripts

If you download that directory and then run the `simulate_*` files they should execute. If in the notebook plots should appear.

**Comment by moorepants** [comment]
Confirmed that this now works!
![Selection_584](https://user-images.githubusercontent.com/276007/66055122-e9a61780-e4e9-11e9-9243-1bb150fd4c84.png)

So, to confirm, we've switch to apt install octave over conda installed?

**Comment by moorepants** [comment]
I see that is the case here: https://github.com/LibreTexts/default-env/commit/83cf5a928f88b561ed98fcb114bbda657b65bbe6

Great! Thanks.

**Comment by celine168** [comment]
Yes, installing octave using apt worked.
