### ISSUE TITLE
Packges are not installed into the root/base conda environment

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/default-env#4]
It seems like this creates a conda env called "notebook" and puts the packages in that.

```
(base) jovyan@jupyter-jasonmoore:~$ ipython
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]:
Do you really want to exit ([y]/n)? y
(base) jovyan@jupyter-jasonmoore:~$ which ipython
/srv/conda/envs/notebook/bin/ipython
(base) jovyan@jupyter-jasonmoore:~$ conda info

     active environment : base
    active env location : /srv/conda
            shell level : 2
       user config file : /home/jovyan/.condarc
 populated config files : /srv/conda/.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : /srv/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /srv/conda/pkgs
                          /home/jovyan/.conda/pkgs
       envs directories : /srv/conda/envs
                          /home/jovyan/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/4.15.0-51-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:0
             netrc file : None
           offline mode : False

(base) jovyan@jupyter-jasonmoore:~$ ipython
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sympy

In [2]:
```

These packages need to be installed in the root/base conda environment. In particular, nb_conda_kernels will not work as expected unless in the root/base conda env.

What dockerfile is this using? I'd like to see how things are setup. It seems like an odd setup as it stands.

**Comment by moorepants** [comment]
This shows that sympy was not installed in the base/root env:

```
(base) jovyan@jupyter-jasonmoore:~$ /srv/conda/bin/python
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'sympy'
>>>
```

**Comment by celine168** [comment]
We used repo2docker to convert this repo to [this Docker image](https://cloud.docker.com/u/libretexts/repository/docker/libretexts/default-env).

I think a better way would be to build on top of an existing notebook from [docker stacks](https://github.com/jupyter/docker-stacks). For example, the [scipy notebook](https://github.com/jupyter/docker-stacks/blob/master/scipy-notebook/Dockerfile) already has many of the existing packages we need.

Would you rather that the default environment have the bare minimum packages or would you not mind having extra packages? If the former, I will try to build on top of the [minimal notebook](https://github.com/jupyter/docker-stacks/tree/master/minimal-notebook).

**Comment by celine168** [comment]
I'm going to remove the unnecessary packages from the scipy notebook.

**Comment by moorepants** [comment]
I'd prefer that the default image has a lot. Users will likely want everything that is in scipy notebook and more.

**Comment by moorepants** [comment]
Note also that we need to support Python, R, Julia, Octave, and Sage as a default set. So we probably want to pick a base dockerfile that has all that already setup.

**Comment by celine168** [comment]
Out of curiosity, do we want nb_grader in the default environment?

I'm thinking of building on top of the [datascience notebook](https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook) which already has Python, R, and Julia. Will look into getting Octave and Sage up.

**Comment by celine168** [comment]
The Default Environment should now have all of the listed packages in the root environment. Dockerfile is now up in the repo.

Octave and Sage are not supported yet.

**Comment by moorepants** [comment]
> Out of curiosity, do we want nb_grader in the default environment?

Likely but we are going to need to test these out. I'm not quite sure how an instructor's account will be able to access students with that tool.

**Comment by celine168** [comment]
Since packages are installed in the root environment, I'm going to close.
