### ISSUE TITLE
Removing SageMath

### ISSUE THREAD

**Issue by rkevin-arch** [LibreTexts/default-env#46]
Is SageMath being used at the moment? As far as I can tell, no one is using it. In the process of creating a new repo2docker based default environment, we have discovered that it causes many problems, from the conda dependencies resolving forever to installing different conflicting versions of python and python packages when installed using apt. If no users are using SageMath, I think we should remove it as a kernel option.

**Comment by moorepants** [comment]
It may not be used in a major project right now, but this should not be removed. We want to support sage and kernels for sage.

**Comment by moorepants** [comment]
I also don't think that installing Sage via conda is the best approach at the moment. In the future the conda install sage may work better, but for now it doesn't. Sage should be installed as per the recommended installation instructions provided by the sage project and we can install the sage kernel via conda to connect it.

**Comment by rkevin-arch** [comment]
In that case, do you mind if the sage environment and kernel be in a separate image? Installing the `sage` package in conda takes more than an hour to solve dependencies (and I cancelled it after the 1 hour mark), and installing it through apt will add many conflicting versions of python and python packages compared to what we currently have (to be honest, I'm not sure how our current setup (which installs it via apt) works considering how much these packages conflict)

**Comment by moorepants** [comment]
There should be no conflicts if installed via apt. I'm not sure what conflicts you are referring to. Do not install via conda as it isn't fully developed.

I want to keep everything in a single environment, as we currently have it.

**Comment by rkevin-arch** [comment]
For example, conda installs python 3.7.6 while installing sagemath will install python3.6 and python2.7 from apt, along with installing all the python packages like `matplotlib` 2.1.1 and `numpy` 1.13.3 (compared to conda's 3.3.0 and 1.19.1), the entire jupyter environment like `jupyter-core` 4.4.0 and `ipython` 5.5.0 (compared to conda's 4.6.1 and 7.11.1), all the dependencies that jupyter needs like `python-tornado` 4.5.3 (compared to conda's 6.0.3), and so on. It's a very long list (apt installes 453 dependencies, most of which seem to overlap with conda). I'm not sure if 1. having those conflicting versions of everything would cause problems for the user using other kernels normally, and 2. even if conda tries to override the ones installed by apt, if all those differing versions would cause SageMath any problems.

**Comment by moorepants** [comment]
There may be some path adjustments we have to make to get everything working properly, but in general conda installed packages will use conda installed dependencies and sage will ignore the conda installed packages and use the apt dependencies. The two installations are separate. The only thing that will tie them together is pointing the jupyter sage kernel to the apt package.

**Comment by rkevin-arch** [comment]
The sage kernel is installed via apt, so that isn't an issue. We will just use apt to install sagemath then.
