### ISSUE TITLE
Downgrading Conda to Install Octave

### ISSUE THREAD

**Issue by celine168** [LibreTexts/default-env#5]
After installing the Python packages, I had trouble installing the Octave kernel. I kept running into an error like this:
```
Step 6/7 : RUN conda install --quiet --yes     'octave=4.2.1'     'octave_kernel=0.28.*' &&     conda clean --all -f -y &&     fix-permissions $CONDA_DIR &&     fix-permissions /home/$NB_USER
 ---> Running in f1e7a57a9c54
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with current_repodata.json, will retry with next repodata source.
Initial quik solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: ...working... failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
```

Extra redundant info: if I go into the Docker image with `docker run --rm -it <last-built-image> bash -il`, I'll get the same error when running `conda install octave=<ver>`.

I believe this may be an issue in conda, according to https://github.com/conda/conda/issues/9004#issuecomment-516673591. One way to workaround it is downgrading conda to version `4.6.14`, which is what is in the Dockerfile right now but I know this is bad practice. [Link to commands of downgrade](https://github.com/LibreTexts/default-env/blob/b017df20a95a8aa45b899d6a2fb937aa9b501a4f/rich-default/Dockerfile#L26) The Octave kernel is now in the environment.

I find it strange though how the other packages seemed to install fine with conda, so it might be a problem on my end.

The issue says that the `4.7.11` release of conda should fix the problem, so I was waiting until then and then fixing the Dockerfile.

**Comment by moorepants** [comment]
Conda gets updated frequently. I often never have the latest version. It is probably ok for us to be a minor version (or two) behind.

**Comment by moorepants** [comment]
Another option is to install octave using apt instead of conda.

**Comment by moorepants** [comment]
Nevermind that last comment, seems the issue is with octave_kernel, which you'll need to install with conda.

**Comment by moorepants** [comment]
One issue is that trying to install a collection of packages at pinned versions may cause a version incompatibility.

With conda, it is easiest to install without version pins and once conda discovers a compatible set, then you can pin that set for your reproducible environment.

**Comment by moorepants** [comment]
This works for me with conda 4.7.10.

```
moorepants@agni:~$ /home/moorepants/miniconda/bin/conda info

     active environment : None
       user config file : /home/moorepants/.condarc
 populated config files : /home/moorepants/.condarc
          conda version : 4.7.10
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /home/moorepants/miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/moorepants/miniconda/pkgs
                          /home/moorepants/.conda/pkgs
       envs directories : /home/moorepants/miniconda/envs
                          /home/moorepants/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.10 requests/2.21.0 CPython/3.7.3 Linux/5.0.0-23-generic ubuntu/19.04 glibc/2.29
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
moorepants@agni:~$ /home/moorepants/miniconda/bin/conda create -n octave-test octave octave_kernel python julia jupyter
moorepants@agni:~$ /home/moorepants/miniconda/bin/conda list -n octave-test
# packages in environment at /home/moorepants/miniconda/envs/octave-test:
#
# Name                    Version                   Build  Channel
...
julia                     1.0.3           blas_openblash12d65f3_2  [blas_openblas]  conda-forge
jupyter                   1.0.0                      py_2    conda-forge
...
octave                    4.2.1               hb4c947d_12    conda-forge
octave_kernel             0.31.0                     py_0    conda-forge
...
python                    3.7.3                h33d41f4_1    conda-forge
...
moorepants@agni:~$ /home/moorepants/miniconda/envs/octave-test/bin/julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.3
 _/ |\__'_|_|_|\__'_|  |  conda-forge-julia release
|__/                   |

julia> 
moorepants@agni:~$ /home/moorepants/miniconda/envs/octave-test/bin/octave
moorepants@agni:~$ /home/moorepants/miniconda/envs/octave-test/bin/octave --no-gui
/home/conda/feedstock_root/build_artifacts/octave_1564063268657/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/libexec/octave/4.2.1/exec/x86_64-pc-linux-gnu/octave-gui: failed to exec '/home/conda/feedstock_root/build_artifacts/octave_1564063268657/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/libexec/octave/4.2.1/exec/x86_64-pc-linux-gnu/octave-gui'
/home/moorepants/miniconda/envs/octave-test/bin/octave: No such file or directory
moorepants@agni:~$ /home/moorepants/miniconda/envs/octave-test/bin/python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

Octave didn't seem to work at the command line but works when I open jupyter from that environment:
![2019-08-04_11-01](https://user-images.githubusercontent.com/276007/62427396-601fc800-b6a7-11e9-9b74-fd4d38dec7d7.png)

**Comment by moorepants** [comment]
I did notice that this works:
```
moorepants@agni:~$ /home/moorepants/miniconda/envs/octave-test/bin/octave-cli
GNU Octave, version 4.2.1
Copyright (C) 2017 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "x86_64-pc-linux-gnu".

Additional information about Octave is available at http://www.octave.org.

Please contribute if you find this software useful.
For more information, visit http://www.octave.org/get-involved.html

Read http://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.

octave:1> 
```

**Comment by celine168** [comment]
Are you suggesting to take out specifying the versions, and then add them back in later?

**Comment by moorepants** [comment]
Yes, essentially. For example, we could build up the default set of conda packages without specifying versions for now. Then come August 20th, we pin them to the current working set. After that, we would test upgrade on our staging cluster with them unpinned and then when it works, update the pins in production and upgrade. This method would keep the production environments reproducible and allow relatively painless upgrades.

**Comment by celine168** [comment]
```
UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (hdf5):

  - octave -> hdf5[version='1.10.1.*,>=1.10.5,<1.10.6.0a0']

The following specifications were found to be incompatible with each other:



Package hdf5 conflicts for:
hdf5=1.10
h5py=2.9 -> hdf5[version='>=1.10.4,<1.10.5.0a0']
h5py=2.9 -> hdf5[version='>=1.10.4,<1.10.5.0a0',build=mpi_mpich_*]
h5py=2.9 -> hdf5[version='>=1.10.4,<1.10.5.0a0',build=mpi_openmpi_*]
```
I believe the error may have something to do with this.

**Comment by celine168** [comment]
I was building on top of the datascience notebook, which builds on top of the scipy notebook. These notebooks will always have changing versions of packages since they are hosted on Github/DockerHubby Jupyter. 
I could make copies of the current notebooks' Dockerfiles onto our DockerHub and manually change them, or combine them into a new Dockerfile entirely.

**Comment by moorepants** [comment]
That looks like octave and h5py both require very specific versions of hdf5 that are not compatible in the same environment. That is pretty annoying. You could open an issue(s) on the conda forge octave and/or h5py feedstocks showing that it seems to be impossible to install them in the same environment. (this is one of the downsides of conda, i.e. all packages in a given environment have to share the same dependencies)

**Comment by moorepants** [comment]
>  I could make copies of the current notebooks' Dockerfiles onto our DockerHub and manually change them, or combine them into a new Dockerfile entirely.

I think we are going to want to have full control of the conda installed packages in our dockerfile, otherwise you'll hit issues like the octave/h5py one because we can't unpin package versions.

**Comment by celine168** [comment]
As for OS dependencies, I think it would still be safe to rely on the [minimal notebook](https://github.com/jupyter/docker-stacks/blob/master/minimal-notebook/Dockerfile) (which relies on the [base notebook](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile)). We're only worried about the compatibility of the extra conda packages (besides jupyterhub/jupyterlab) right?

I think I can tag the specific release of the minimal-notebook.

**Comment by moorepants** [comment]
> As for OS dependencies, I think it would still be safe to rely on the minimal notebook (which relies on the base notebook). We're only worried about the compatibility of the extra conda packages (besides jupyterhub/jupyterlab) right?

That sounds fine.

**Comment by celine168** [comment]
I'm going to close since the installation of the Octave kernel seems to work fine now.

**Comment by celine168** [comment]
Just wanted to add that the initial problem with installing Octave may have not come from including everything under one `conda install` command, but from the previous pinned versions of the packages Jupyter specified in their own Dockerfiles.
