### ISSUE TITLE
Octave Packages

### ISSUE THREAD

**Issue by celine168** [LibreTexts/default-env#6]
Are there specific Octave packages that should be installed?
I've tried running a few commands like the ones in [this example notebook](https://github.com/binder-examples/octave/blob/master/index.ipynb), but they return errors.

**Comment by moorepants** [comment]
Can you post the errors?

**Comment by moorepants** [comment]
I think that notebook should work with the base octave install. We don't need to install any octave packages until people request them.

**Comment by celine168** [comment]
```
# In Cell
tx = ty = linspace (-8, 8, 41)';
[xx, yy] = meshgrid (tx, ty);
r = sqrt (xx .^ 2 + yy .^ 2) + eps;
tz = sin (r) ./ r;
mesh (tx, ty, tz);

# Output
error: 'meshgrid' undefined near line 1 column 10
error: 'xx' undefined near line 1 column 11
error: 'r' undefined near line 1 column 11
error: 'tz' undefined near line 1 column 15
```

I'm going to try running docker build again. Since `pkg` isn't working, there's probably something wrong with the Octave installation itself.

**Comment by moorepants** [comment]
`meshgrid` is a builtin function in octave and should work without any special packages, e.g.:
```
moorepants@paravati:~$ octave
GNU Octave, version 4.4.1
Copyright (C) 2018 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "x86_64-pc-linux-gnu".

Additional information about Octave is available at https://www.octave.org.

Please contribute if you find this software useful.
For more information, visit https://www.octave.org/get-involved.html

Read https://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.

octave:1> meshgrid
error: Invalid call to meshgrid.  Correct usage is:

 -- [XX, YY] = meshgrid (X, Y)
 -- [XX, YY, ZZ] = meshgrid (X, Y, Z)
 -- [XX, YY] = meshgrid (X)
 -- [XX, YY, ZZ] = meshgrid (X)

Additional help for built-in functions and operators is
available in the online version of the manual.  Use the command
'doc <topic>' to search the manual index.

Help and information about Octave is also available on the WWW
at https://www.octave.org and via the help@octave.org
mailing list.
```

**Comment by celine168** [comment]
I realized that, it's probably something wrong with the Octave installation.

**Comment by celine168** [comment]
I realized that the compatibility issues came from having different `conda install` blocks in the Dockerfiles. I plan on putting all of the packages under one `conda install` block so hopefully the dependency issues can sort themselves out.

Also, it turns out that functions like `meshgrid` and `plot` in `octave-kernel` depends on the `gnuplot` and `ghostscript` packages (tested it out and it works). Will be including those packages.

**Comment by celine168** [comment]
Octave kernel now seems to work! Closing issue.
