### ISSUE TITLE
SageMath Doesn't Work

### ISSUE THREAD

**Issue by celine168** [LibreTexts/default-env#7]
Maybe due to it relying on the wrong Python version, as explained here: https://bytesofcomputerwisdom.home.blog/2019/03/23/sagemathwont-run-no-module-named-sage-repl/

I need to test it out.

**Comment by moorepants** [comment]
One option is that we don't support it from the start. I think that is ok. It may be that you can only install a fully working sage in a unique docker environment.

**Comment by celine168** [comment]
You can now run Sage from the terminal, but cannot start a SageMath Notebook or Console from the Launcher. You can see this in the Test Environment. 
There are still a couple of solutions I found that I want to try out.

**Comment by celine168** [comment]
SageMath now works in the Rich Default Environment along with Octave and the other kernels.
This blog post helped solve the problem: https://bytesofcomputerwisdom.home.blog/2019/03/23/sagemathwont-run-no-module-named-sage-repl/
Needed to follow both parts for SageMath to work both in the Notebook and Terminal, automated those steps here: 
https://github.com/LibreTexts/default-env/blob/ccc6413d1656c97775552a67264a50bad68eeb18/rich-default/Dockerfile#L138-L144
