### ISSUE TITLE
Error in getting banner for R console

### ISSUE THREAD

**Issue by celine168** [LibreTexts/default-env#8]
The R console seems to work, but does not generate a banner when opened.

![image](https://user-images.githubusercontent.com/22624020/62731247-91193900-b9d6-11e9-8a3c-49e4c12e1647.png)

This doesn't seem to be an issue with the environments made by Jupyter (e.g. the Datascience environment), so I assume that this is a problem on our end.

**Comment by moorepants** [comment]
I think you'll need to open an issue on Jupyterlab's repo or ask on discourse.

**Comment by celine168** [comment]
It seems like updating JupyterLab from https://github.com/LibreTexts/default-env/issues/14 (or an earlier action that I didn't notice) fixed the problem.
![image](https://user-images.githubusercontent.com/22624020/64059721-af59fb00-cb76-11e9-8e30-8192b0f3c712.png)
