### ISSUE TITLE
Automating configuration for custom conda environments

### ISSUE THREAD

**Issue by celine168** [LibreTexts/default-env#9]
I described how to manually enable custom conda environments here: https://github.com/LibreTexts/default-env#creating-your-own-custom-conda-environment

I tried to automate the part of creating `.condarc` and adding two lines through the Dockerfile: 
https://github.com/LibreTexts/default-env/blob/ccc6413d1656c97775552a67264a50bad68eeb18/rich-default/Dockerfile#L194-L198

However, Docker seems to have trouble creating and editing this file as it does not show up in the user's home directory. I have tried setting the working directory to home but the file `.condarc` still does not show up in the user's home directory.

**Comment by moorepants** [comment]
I'm fine if we just point people to the instructions so they can manually do this configuration.

**Comment by celine168** [comment]
Asked here: https://discourse.jupyter.org/t/automate-adding-condarc-for-nb-conda-kernels-to-dockerfile/1936

**Comment by moorepants** [comment]
I'm closing in favor of just giving them manual instructions for this.
